device: 0
batch_size: 32
dropout: 0.25
epochs: 70
num_run: 30
cancer_type: gbm
construct_cnv_mrna_edge: True
construct_mt_mrna_edge: True
conv_encode_edge: True
drop_irr_pathway: True
feature_drop: True
final_channels: 32
final_head: 4
freeze_mutual_select_init: True
gnn_name: sage
gnn_pathcnn: True
grn_edge_select_threshold: 0.00001
head_dim: 256
hidden_channels: 64
init_emb: True
init_with_pca: True
learnable_pca: True
model: multilevel_gnn
mute_edge: "12"
mutual_classif: True
mutual_info_mask: True
mutual_info_pca: True
mutual_neighbors: 7
node_embedding: True
node_embedding_dim: 64
num_layer_head: 2
num_layers: 2
pathway_global_node: True
pca_indep_loss: True
pca_match_mask: True
pca_sim_dim: 2
pre_concat_age: True
pre_readout_drop: True
random_state: 12345
reverse_mt_attr: True
save_dir: gbm
save_tag: gbm_final
split_shaffle: True
use_age: True
use_column: "stringdb::score"
use_edge_attr: True
value_att_mask: True
weight_balance: True
weighted_edge: True
z_mean: True