batch_size: 64
cancer_type: kirc
construct_cnv_mrna_edge: True
construct_mt_mrna_edge: True
conv_encode_edge: True
device: 0
drop_irr_pathway: True
dropout: 0.25
edge_type: grnboost2
epochs: 140
feature_drop: True
final_channels: 32
final_head: 4
freeze_mutual_select_init: True
global_edge: onehot
gnn_name: sage
gnn_pathcnn: True
head_dim: 512
hidden_channels: 64
init_emb: True
init_with_pca: True
learnable_pca: True
lr: 0.00005
model: multilevel_gnn
mute_edge: "12"
mutual_classif: True
mutual_info_mask: True
mutual_info_pca: True
mutual_neighbors: 15
node_embedding: True
num_layer_head: 2
num_layers: 2
num_run: 30
pathway_global_node: True
pca_dim: 3
pca_indep_loss: True
pca_match_mask: True
pca_sim_dim: 3
pre_readout_drop: True
random_state: 12345
reorder_pathway: True
reverse_mt_attr: True
risk_threshold: 36
save_dir: kirc
save_tag: kirc_final
selected_similarity: True
split_shaffle: True
step: 140
use_column: "stringdb::score"
use_edge_attr: True
value_att_mask: True
weight_balance: True
weighted_edge: True
z_mean: True
pathway_pool_dim: 1
pca_pool_dim: 1